Date and time: 2025-05-26 10:34:53 DatabasFel Kunde inte ansluta till databasen med artikelnummer: DataBasFel123. 
se.kth.iv1350.sellProcess.integration.DatabaseFailureException: Kunde inte ansluta till databasen med artikelnummer: DataBasFel123.
	at se.kth.iv1350.sellProcess.integration.ExternalInventorySystem.getItem(ExternalInventorySystem.java:48)
	at se.kth.iv1350.sellProcess.controller.Controller.scanItem(Controller.java:72)
	at se.kth.iv1350.sellProcess.view.View.startSale(View.java:46)
	at se.kth.iv1350.sellProcess.startup.Main.main(Main.java:17)

